#!/bin/bash
# Phase G - Live monitoring script
# Shows real-time progress of overnight run

cd "$(dirname "$0")"

while true; do
    clear
    echo "=============================================="
    echo "Phase G Extended - Live Monitor"
    echo "=============================================="
    echo "Time: $(date)"
    echo ""

    # Running processes
    running=$(pgrep -af "runner_phase2" | wc -l)
    echo "Running processes: $running"
    echo ""

    # Job log status (if exists)
    if [ -f "results/overnight_joblog.txt" ]; then
        total=$(wc -l < results/overnight_joblog.txt)
        completed=$(grep -c "^[0-9]" results/overnight_joblog.txt 2>/dev/null || echo 0)
        echo "Jobs completed: $((completed - 1))/$((total - 1))"
    fi
    echo ""

    # Latest log activity
    echo "=== Latest log activity ==="
    latest_log=$(ls -t results/*.log 2>/dev/null | head -1)
    if [ -n "$latest_log" ]; then
        echo "Log: $latest_log"
        tail -5 "$latest_log" 2>/dev/null
    fi
    echo ""

    # Synthetics generated
    echo "=== Synthetics generated by config ==="
    for cfg in W1 W2 W3 W4 W5 W6 W7 W8 W9; do
        synth_files=$(ls -1 results/${cfg}*_synth.csv 2>/dev/null | wc -l)
        if [ "$synth_files" -gt 0 ]; then
            total_synth=$(cat results/${cfg}*_synth.csv 2>/dev/null | wc -l)
            echo "  ${cfg}*: $synth_files files, ~$total_synth samples"
        fi
    done
    echo ""

    # Problem classes check
    echo "=== Problem classes (ESFP/ESTJ) in latest files ==="
    for f in $(ls -t results/*_synth.csv 2>/dev/null | head -3); do
        esfp=$(grep -c "ESFP" "$f" 2>/dev/null || echo 0)
        estj=$(grep -c "ESTJ" "$f" 2>/dev/null || echo 0)
        fname=$(basename "$f")
        echo "  $fname: ESFP=$esfp, ESTJ=$estj"
    done

    sleep 30
done
